language : node_js

service : 
  - docker

after_success :
   - pip install --user awscli
   - docker build  -t william/nodetest .
   - eval $(aws ecr get-login --region eu-west-1 --no-include-email)
   - docker tag william/nodetest 938788377650.dkr.ecr.eu-west-1.amazonaws.com/nodetest
   - docker push 938788377650.dkr.ecr.eu-west-1.amazonaws.com/nodetest
   - aws ecs update-service --cluster ecscluster  --service hellonode-WebApp-C65ELNX6K627 --force-new-deployment
