apiVersion: v1
clusters:
- cluster:
    server: "158"
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: frefebob
    username: bob
